### ISSUE TITLE
Option for display a chart with the last day growth

### ISSUE THREAD

**Issue by dasilvacontin** [mach1/bitcoin-price#1]
Using spark.

**Comment by mach1** [comment]
I thought about doing something like that. Should look into it.

**Comment by dasilvacontin** [comment]
Cool :shipit:

**Comment by mach1** [comment]
This can me achieved by using `bitcoin-price -g | spark` for now.

**Comment by dasilvacontin** [comment]
Cool, thanks!

**Comment by dasilvacontin** [comment]
<img width="869" alt="screenshot 2015-12-01 20 56 38" src="https://cloud.githubusercontent.com/assets/1260830/11512370/0ea66a7a-986e-11e5-9ed0-b2f8afd62bb1.png">
:raised_hands:
